---
- hosts: dev29
  remote_user: ipin
  roles:
    - { role: ../roles/docker_install
    #docker_opts: "-H tcp://127.0.0.1:4243 -H unix:///var/run/docker.sock --dns 8.8.8.8 --dns 8.8.4.4"
      }

#- include: integration-tests.yml
