set nocompatible              " required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'
"Plugin 'tmhedberg/SimpylFold'
"Bundle 'Valloric/YouCompleteMe'
"Plugin 'altercation/vim-colors-solarized'
"Plugin 'jnurmine/Zenburn'
"Plugin 'scrooloose/nerdtree'
Plugin 'jiangmiao/auto-pairs'
Plugin 'vim-airline/vim-airline'
"Plugin 'vim-airline/vim-airline-themes'

" Add all your plugins here (note older versions of Vundle used Bundle instead of Plugin)


" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

set splitbelow
set splitright

"split navigations
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Enable folding
set foldmethod=indent
set foldlevel=99
"set cursorline
"set cursorcolumn

" Enable folding with the spacebar
nnoremap <space> za

let g:SimpylFold_docstring_preview=1
au BufNewFile,BufRead *.py
\ set tabstop=4 |
\ set softtabstop=4 |
\ set shiftwidth=4 |
\ set textwidth=79 |
\ set expandtab |
\ set autoindent |
\ set fileformat=unix

au BufNewFile,BufRead *.html
\ set tabstop=2 |
\ set softtabstop=2 |
\ set shiftwidth=2 |

syntax enable
"syntax on
"set go=

"set background=light
"let g:solarized_termcolors=256
"colorscheme solarized

"set background=dark
"colorscheme zenburn
"call togglebg#map("<F5>")

"set guifont=Sauce\ Code\ Powerline:h14.5
set laststatus=2
let g:airline_powerline_fonts=1
set encoding=utf-8
set t_Co=256
set fillchars+=stl:\ ,stlnc:\

"设置终端的配色方式
"set term=xterm-256color
"set termencoding=utf-8
"set background=dark
"set background=light

autocmd BufNewFile *.py :call AddTitle()
function AddTitle()
	call append(0,"#!/usr/bin/env python")
	call append(1,"# -*- coding: utf-8 -*-")
	call append(2,"# Copyright © Sgr")
	call append(3,"# CreateTime: ".strftime("%Y-%m-%d %H:%M:%S"))
	call append(4,"")
endf
