---

- name: Uninstall old versions of Docker
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-engine
    - docker.io
  when: uninstall_previous_docker_versions

- name: Install net LTS kernel for Docker
  apt:
    name: linux-generic-lts-xenial
    state: present
  when: uninstall_previous_docker_versions

- name: Install curl package of Docker
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - python-pip

- name: Copy docker package to server
  copy:
    src: files/package.deb
    dest: /tmp/package.deb
    owner: sgr
    mode: 0755

- name: Install docker.deb package 
  apt: 
    deb: /tmp/package.deb
  notify: delete package

- name: Add user to docker groups
  user:
    name: sgr
    # default is no, set yes increment groups
    append: yes
    groups: docker

- name: Add DOCKER_OPTS in /etc/defalut/docker
  lineinfile:
    path: /etc/default/docker
    line: "DOCKER_OPTS='{{ docker_opts }}'"
  notify: restart docker

- name: Install docker-composer package
  pip:
    name: docker-compose
    state: present
